#!/bin/bash
#
# Copyright 2019 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# Exit on non-zero exit code from subcommand
set -e

# Set trusted-compute-framework project directory relative to this file
PROJECT_DIR=$(cd $(dirname $(dirname $0)) && pwd)

# Make Avalon scripts accessible
PATH=$PROJECT_DIR/bin:$PATH

# Arguments to trigger the tests
DIRECT_MODEL_TESTS=0
BESU_PROXY_MODEL_TESTS=0
GANACHE_PROXY_MODEL_TESTS=0
FABRIC_PROXY_MODEL_TESTS=0
WP_DIRECT_MODEL_TESTS=0
DIRECT_MODEL_SGX_TESTS=0
WP_DIRECT_MODEL_SGX_TESTS=0
BESU_PROXY_MODEL_SGX_TESTS=0
GANACHE_PROXY_MODEL_SGX_TESTS=0
FABRIC_PROXY_MODEL_SGX_TESTS=0
FABRIC_PROXY_MODEL_WP_TESTS=0
FABRIC_PROXY_MODEL_WP_SGX_TESTS=0
BESU_PROXY_MODEL_WP_TESTS=0
BESU_PROXY_MODEL_WP_SGX_TESTS=0
GANACHE_PROXY_MODEL_WP_TESTS=0
GANACHE_PROXY_MODEL_WP_SGX_TESTS=0

main() {

    if [ "$DIRECT_MODEL_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-direct-model-tests.yaml
    elif [ "$BESU_PROXY_MODEL_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-besu-proxy-model-tests.yaml
    elif [ "$GANACHE_PROXY_MODEL_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-ganache-proxy-model-tests.yaml
    elif [ "$FABRIC_PROXY_MODEL_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-fabric-proxy-model-tests.yaml
    elif [ "$WP_DIRECT_MODEL_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-wp-direct-model-tests.yaml
    elif [ "$DIRECT_MODEL_SGX_TESTS" == "1" ]; then
    	run_docker_test ./ci/avalon-direct-model-sgx-tests.yaml
    elif [ "$WP_DIRECT_MODEL_SGX_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-wp-direct-model-sgx-tests.yaml
    elif [ "$BESU_PROXY_MODEL_SGX_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-besu-proxy-model-sgx-tests.yaml
    elif [ "$GANACHE_PROXY_MODEL_SGX_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-ganache-proxy-model-sgx-tests.yaml
    elif [ "$FABRIC_PROXY_MODEL_SGX_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-fabric-proxy-model-sgx-tests.yaml
    elif [ "$FABRIC_PROXY_MODEL_WP_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-fabric-proxy-model-wp-tests.yaml
    elif [ "$FABRIC_PROXY_MODEL_WP_SGX_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-fabric-proxy-model-wp-sgx-tests.yaml
    elif [ "$BESU_PROXY_MODEL_WP_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-besu-proxy-model-wp-tests.yaml
    elif [ "$BESU_PROXY_MODEL_WP_SGX_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-besu-proxy-model-wp-sgx-tests.yaml
    elif [ "$GANACHE_PROXY_MODEL_WP_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-ganache-proxy-model-wp-tests.yaml
    elif [ "$GANACHE_PROXY_MODEL_WP_SGX_TESTS" == "1" ]; then
        run_docker_test ./ci/avalon-ganache-proxy-model-wp-sgx-tests.yaml
    fi

}

while getopts "dbfgwstuvxyzijkl" opt; do
    case $opt in
        d)
            DIRECT_MODEL_TESTS=1
            ;;
        b)
            BESU_PROXY_MODEL_TESTS=1
            ;;
	g)
            GANACHE_PROXY_MODEL_TESTS=1
	    ;;
        f)
            FABRIC_PROXY_MODEL_TESTS=1
            ;;
	w)
	    WP_DIRECT_MODEL_TESTS=1
	    ;;
	s)
            DIRECT_MODEL_SGX_TESTS=1
	    ;;
	t)
            WP_DIRECT_MODEL_SGX_TESTS=1
	    ;;
	u)
            BESU_PROXY_MODEL_SGX_TESTS=1
	    ;;
	v)
	    GANACHE_PROXY_MODEL_SGX_TESTS=1
	    ;;
	x)
            FABRIC_PROXY_MODEL_SGX_TESTS=1
	    ;;
        y)
            FABRIC_PROXY_MODEL_WP_TESTS=1
            ;;
        z)
            FABRIC_PROXY_MODEL_WP_SGX_TESTS=1
            ;;
        i)
            BESU_PROXY_MODEL_WP_TESTS=1
            ;;
        j)
            BESU_PROXY_MODEL_WP_SGX_TESTS=1
            ;;
        k)
            GANACHE_PROXY_MODEL_WP_TESTS=1
            ;;
        l)
            GANACHE_PROXY_MODEL_WP_SGX_TESTS=1
            ;;
        h)
            echo "Usage: run_tests script to trigger tests for direct/proxy model"
	    echo "    run_tests -d       To run (Singleton) direct model tests."
	    echo "    run_tests -f       To run (Singleton) fabric proxy model  tests."
	    echo "    run_tests -b       To run (Singleton) besu ethereum proxy model tests."
	    echo "    run_tests -g       To run (Singleton) ganache ethereum proxy model tests."
	    echo "    run_tests -w       To run (Worker Pool) direct model tests."
	    echo "    run_tests -s       To run (Singleton) direct model SGX tests."
	    echo "    run_tests -t       To run (Worker Pool) direct model SGX tests."
	    echo "    run_tests -u       To run (Singleton) besu ethereum proxy model SGX tests."
	    echo "    run_tests -v       To run (Singleton) ganache ethereum proxy model SGX tests."
	    echo "    run_tests -x       To run (Singleton) fabric proxy model SGX tests."
            echo "    run_tests -y       To run (Worker Pool) fabric proxy model tests."
            echo "    run_tests -z       To run (Worker Pool) fabric proxy model SGX tests."
            echo "    run_tests -i       To run (Worker Pool) besu ethereum proxy model tests."
            echo "    run_tests -j       To run (Worker Pool) besu ethereum proxy model SGX tests."
            echo "    run_tests -k       To run (Worker Pool) ganache ethereum proxy model tests."
            echo "    run_tests -l       To run (Worker Pool) ganache ethereum proxy model SGX tests."
	    exit 0
            ;;
        \?)
           echo "Invalid Option: -$OPTARG" 1>&2
           exit 2
            ;;
    esac
done
main
