apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.propose.name }}
spec:
  template:
    metadata:
      labels:
        app: request
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ .Values.propose.name }}
        image: {{ .Values.shell.name }}-dev:latest
        imagePullPolicy: Never
        command: ["/bin/bash"]
        args: ["/project/avalon/docker/k8s/propose_requests.sh"]
